spring:
  jackson:
    parser:
      allow-numeric-leading-zeros: true
  http:
    converters:
      preferred-json-mapper: jackson
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/msorder?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        check_nullability: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
mq:
  queues:
    orders: orders